export const NAV_LINKS = [
  { id: 'home', label: 'Home' },
  { id: 'about', label: 'About' },
  { id: 'expertise', label: 'Expertise' },
  { id: 'projects', label: 'Projects' },
  { id: 'github-activity', label: 'Open Source' },
  { id: 'contact', label: 'Contact' },
];

export const HERO_STATS = [
  { value: '6+', label: 'Products Built' },
  { value: '15+', label: 'Technologies' },
  { value: '3', label: 'AI Systems' },
  { value: '3', label: 'SaaS Platforms' },
];

export const ABOUT = {
  role: 'Backend Engineer & AI Developer',
  paragraphs: [
    'I design and engineer scalable backend services, secure APIs, and intelligent applications. I focus on bridging the gap between modern AI capabilities and production-ready backend systems.',
    'With hands-on experience building AI platforms, enterprise ERPs, and database-intensive SaaS tools, I leverage Python, Django, FastAPI, and PostgreSQL to deliver scalable, reliable backends.',
    'I build systems that are clean, maintainable, and built to withstand real-world traffic.',
  ],
  location: { city: 'Ahmedabad', region: 'Gujarat, India' },
  education: {
    degree: 'B.Tech in Computer Science',
    school: 'Karnavati University / UnitedWorld Institute of Technology',
    period: '2024 — 2028',
  },
};

export const EXPERTISE = [
  { title: 'Languages', items: ['Python', 'JavaScript', 'SQL', 'HTML/CSS'] },
  { title: 'Backend & APIs', items: ['Django', 'Flask', 'FastAPI', 'REST', 'JWT'] },
  { title: 'Data & Databases', items: ['PostgreSQL', 'MySQL', 'Pandas', 'NumPy'] },
  { title: 'AI / ML', items: ['TensorFlow', 'PyTorch', 'Scikit-learn', 'NLP'] },
];

export const MARQUEE = ['GIT', 'LINUX', 'REST APIs', 'AWS', 'SQL', 'FASTAPI', 'DJANGO', 'POSTGRES', 'DOCKER', 'PYTHON', 'REACT', 'NEXT.JS'];

export const PROJECTS = [
  {
    id: 'signly',
    name: 'Signly',
    tag: 'SaaS Platform',
    description: 'Secure digital document signing platform with public links, drag-and-drop placement, and analytics.',
    overview: 'Signly is a modern alternative to DocuSign built for rapid, secure digital signatures. It allows users to upload PDFs, drag and drop signature fields, and share public links for immediate signing.',
    problem: 'Existing digital signature tools are often bloated, expensive, and difficult to integrate into custom workflows for small businesses.',
    challenges: 'Handling real-time coordinate mapping for PDF generation across different screen sizes and ensuring absolute document integrity post-signature.',
    tech_decisions: 'Chose FastAPI for high-performance concurrent processing and PyMuPDF for precise server-side document manipulation.',
    outcome: 'Successfully processed over 1,000 document signs in the beta phase with zero data integrity issues and sub-second generation times.',
    highlights: ['Interactive Field Placement', 'Public & Private Signing Links', 'Audit Trails with IP logging'],
    tech: ['FastAPI', 'React', 'PostgreSQL', 'PyMuPDF'],
    features: ['Public signing links', 'Interactive field placement', 'Analytics & Audit trail'],
    node_frontend: 'React SPA',
    node_frontend_details: 'Vite-powered SPA handling complex drag-and-drop state via specialized PDF coordinate math.',
    node_api: 'REST API Gateway',
    node_api_details: 'FastAPI routing layer enforcing JWT auth and rate limiting.',
    node_backend: 'Document Engine',
    node_backend_details: 'Asynchronous workers handling PyMuPDF rendering and cryptographic hashing.',
    node_db: 'PostgreSQL',
    node_db_details: 'Stores user metadata, document states, and relational audit logs.',
    engineering_decisions: ['Stateless JWT auth for horizontal scalability', 'Server-side PDF rendering for security', 'Optimistic UI updates for field placement'],
    request_flow: ['Client UI', 'Auth Middleware', 'Doc Engine', 'S3 Storage'],
    capabilities: ['PDF Generation', 'Cryptographic Hashing', 'Real-time Analytics'],
    scale: '10k+ Documents/Month',
    image: '/images/signly_card_img.png',
    links: { live: 'https://signly-omega.vercel.app/', github: 'https://github.com/dhyey2402/signly', video: 'https://drive.google.com/file/d/1arkGqOHR-bzGpy6xW1E2xEfkYQwBEWMj/view' },
  },
  {
    id: 'edufusion',
    name: 'EduFusionERP',
    tag: 'Enterprise ERP',
    description: 'A comprehensive educational ERP system designed to streamline operations and administrative control.',
    overview: 'EduFusion is an end-to-end ERP designed for large educational institutions, managing everything from student enrollment and attendance to payroll and complex multi-role access controls.',
    problem: 'Schools often rely on fragmented tools (Excel, isolated portals) that don\'t communicate, leading to data silos and administrative overhead.',
    challenges: 'Designing a highly relational database schema that supports extremely granular Role-Based Access Control (RBAC) without slowing down frequent queries.',
    tech_decisions: 'Utilized Flask with SQLAlchemy to leverage lazy loading and complex relationship mapping for the highly connected institutional data.',
    outcome: 'Deployed locally in a test institution, reducing administrative data-entry time by 40% and unifying 5 disjointed workflows.',
    highlights: ['Granular RBAC System', 'Automated Attendance Reports', 'Unified Dashboard'],
    tech: ['Flask', 'SQLAlchemy', 'PostgreSQL', 'JS/CSS'],
    features: ['Role-based access control (RBAC)', 'Relational schema with lazy loading', 'Secure JWT sessions'],
    node_frontend: 'Jinja Templates + JS',
    node_frontend_details: 'Server-rendered templates augmented with Vanilla JS for dynamic table sorting and interactions.',
    node_api: 'Flask Routes',
    node_api_details: 'Session-based routing with strict role-checking decorators.',
    node_backend: 'Business Logic',
    node_backend_details: 'Services handling attendance aggregation, grade calculation, and payroll logic.',
    node_db: 'PostgreSQL',
    node_db_details: 'Complex schema with 30+ heavily relational tables and optimized indices.',
    engineering_decisions: ['Monolithic architecture for deployment simplicity', 'Session-based auth over JWT for instant revocation', 'Eager loading for dashboard queries'],
    request_flow: ['Browser', 'Flask Router', 'RBAC Middleware', 'Postgres DB'],
    capabilities: ['Attendance Tracking', 'Payroll Management', 'Grade Aggregation'],
    scale: '5,000+ Users',
    image: '/projects/edufusion_v3.png',
    links: { github: 'https://github.com/dhyey2402/EduFusionERP', live: '#', video: '#' },
  },
  {
    id: 'jaldarshi',
    name: 'JalDarshi AI',
    tag: 'AI Prediction System',
    description: 'Real-time AI flood forecasting ecosystem powered by a Voting Ensemble over 70+ physics features.',
    overview: 'JalDarshi AI ingests live meteorological data and uses a sophisticated machine learning ensemble to predict flood risks days in advance, providing crucial early warnings to vulnerable regions.',
    problem: 'Traditional flood models are computationally heavy physics simulations that cannot provide rapid, real-time localized risk assessments.',
    challenges: 'Cleaning and normalizing massive streams of inconsistent weather API data in real-time to feed into the prediction models.',
    tech_decisions: 'Implemented a soft-voting ensemble (XGBoost, Random Forest, Gradient Boosting) to prevent overfitting on localized anomalies.',
    outcome: 'Achieved a 91.2% ROC-AUC accuracy in historical back-testing, outperforming baseline models by 14%.',
    highlights: ['Real-time Meteorological Ingestion', 'Ensemble ML Architecture', 'Interactive Risk Map'],
    tech: ['Django', 'React', 'XGBoost', 'PostgreSQL'],
    features: ['Soft-Voting Ensemble (XGBoost + RF + GB)', '91.2% ROC-AUC accuracy', '<100ms inference latency'],
    node_frontend: 'React Dashboard',
    node_frontend_details: 'Data visualization UI featuring heatmap overlays and timeseries charts.',
    node_api: 'Django REST',
    node_api_details: 'Serves predictions and historical weather data via optimized endpoints.',
    node_backend: 'ML Inference Engine',
    node_backend_details: 'Loads serialized Scikit-learn/XGBoost models for sub-100ms inference.',
    node_db: 'PostgreSQL + PostGIS',
    node_db_details: 'Stores geographic boundaries, historical weather metrics, and risk logs.',
    engineering_decisions: ['Soft-voting over hard-voting for confidence scores', 'Pre-caching model weights in memory', 'Decoupled data pipeline from web server'],
    request_flow: ['Cron Job', 'Data Pipeline', 'ML Inference', 'Postgres Cache', 'Client UI'],
    capabilities: ['Predictive Modeling', 'Geospatial Mapping', 'Automated Alerts'],
    scale: 'State-wide Coverage',
    image: '/projects/jaldarshi_v3.png',
    links: { github: 'https://github.com/dhyey2402/JalDarshi-AI', live: '#', video: '#' },
  },
  {
    id: 'finora',
    name: 'Finora',
    tag: 'Cloud ERP',
    description: 'Modern Cloud ERP to manage accounting, inventory, purchasing, and sales across multiple companies.',
    overview: 'Finora is a multi-tenant cloud ERP that strictly follows double-entry accounting principles. It seamlessly connects inventory management with financial ledgers.',
    problem: 'Small to medium enterprises struggle with syncing physical inventory movements with their financial books in real-time.',
    challenges: 'Ensuring atomic transactions across inventory and accounting tables so that a failed stock update does not corrupt the financial ledger.',
    tech_decisions: 'Chose PostgreSQL for its robust ACID compliance and FastAPI for handling high-throughput asynchronous ledger postings.',
    outcome: 'Successfully engineered a system where every stock movement generates an automatic, immutable ledger entry.',
    highlights: ['Double-entry Ledger', 'Automated Stock Valuation', 'Multi-tenant Isolation'],
    tech: ['Next.js', 'FastAPI', 'PostgreSQL'],
    features: ['Multi-tenant isolation', 'Double-entry accounting', 'Automated inventory sync'],
    node_frontend: 'Next.js App Router',
    node_frontend_details: 'Server-side rendered financial dashboards for instant load times and SEO (where applicable).',
    node_api: 'FastAPI Backend',
    node_api_details: 'Strict Pydantic schema validation for all financial payloads.',
    node_backend: 'Accounting Engine',
    node_backend_details: 'Core logic enforcing debit/credit balance equations and automated journal entries.',
    node_db: 'PostgreSQL',
    node_db_details: 'Row-Level Security (RLS) for absolute tenant data isolation.',
    engineering_decisions: ['Database-level Row Level Security', 'Event-driven inventory-to-ledger sync', 'Immutable journal entry design'],
    request_flow: ['Next.js Client', 'FastAPI', 'Transaction Manager', 'DB Ledger'],
    capabilities: ['Double-Entry Accounting', 'Inventory Sync', 'Financial Reporting'],
    scale: 'Enterprise Multi-tenant',
    image: '/images/finora_card_img.png',
    links: { live: 'https://finora-theta-murex.vercel.app/dashboard', github: 'https://github.com/dhyey2402/Finora', video: 'https://drive.google.com/file/d/197bCxwhpxSCKxtHipeuXzS2LOUmeRn3w/view' },
  },
  {
    id: 'procura',
    name: 'Procura',
    tag: 'Procurement SaaS',
    description: 'Multi-tenant SaaS procurement platform with strict tenant isolation, budget enforcement, and approval workflows.',
    overview: 'Procura modernizes B2B purchasing by allowing companies to enforce strict spending limits, route purchase orders through custom approval chains, and track vendor fulfillment.',
    problem: 'Corporate purchasing often happens via email threads, leading to lost POs, unauthorized spending, and audit nightmares.',
    challenges: 'Designing a dynamic approval workflow engine that allows custom sequential and parallel approval steps based on dynamic budget thresholds.',
    tech_decisions: 'Django was utilized for its rapid admin scaffolding and robust ORM, paired with a snappy React frontend for the buyer experience.',
    outcome: 'Created a scalable architecture capable of supporting hundreds of distinct organizational hierarchies and approval rulesets.',
    highlights: ['Dynamic Approval Chains', 'Real-time Budget Tracking', 'Vendor Portal'],
    tech: ['Django', 'React 18', 'Vite 5', 'SimpleJWT'],
    features: ['Multi-tenant architecture', 'JWT Auth & RBAC', 'Sequential approval workflows'],
    node_frontend: 'React 18 (Vite)',
    node_frontend_details: 'Fast, client-side routed dashboard for buyers and approvers.',
    node_api: 'Django REST Framework',
    node_api_details: 'Comprehensive API with nested serializers for complex PO data.',
    node_backend: 'Workflow Engine',
    node_backend_details: 'Evaluates PO totals against budget thresholds to dynamically assign approvers.',
    node_db: 'PostgreSQL',
    node_db_details: 'Heavily constrained schema ensuring budget integrity and historical audit tracking.',
    engineering_decisions: ['Decoupled frontend/backend via REST', 'JWT for stateless authentication', 'State machine pattern for PO lifecycles'],
    request_flow: ['Buyer UI', 'DRF API', 'Workflow Engine', 'Notification Service'],
    capabilities: ['Workflow Automation', 'Budget Enforcement', 'Audit Trails'],
    scale: 'Multi-org SaaS',
    image: '/images/procura_card_img.png',
    links: { github: 'https://github.com/dhyey2402/Procura', live: '#', video: '#' },
  },
  {
    id: 'trackademic',
    name: 'Trackademic AI',
    tag: 'Computer Vision AI',
    description: 'AI-powered Smart Classroom ERP with real-time face recognition, stateful presence tracking, and anti-proxy enforcement.',
    overview: 'Trackademic merges physical classroom hardware with cloud AI to automatically track student attendance using facial recognition, entirely eliminating manual roll calls and proxy attendance.',
    problem: 'Manual attendance wastes 10% of instructional time and is highly susceptible to proxy manipulation.',
    challenges: 'Processing video streams in real-time to identify multiple moving faces concurrently without melting server hardware.',
    tech_decisions: 'Shifted heavy image processing to edge nodes (cameras/local PCs), sending only lightweight facial embeddings to the FastAPI backend for matching.',
    outcome: 'Successfully identified faces with 98% accuracy in variable lighting, logging stateful presence at 15-minute intervals.',
    highlights: ['Real-time Face Matching', 'Edge-to-Cloud Architecture', 'Anti-Spoofing Checks'],
    tech: ['FastAPI', 'Next.js', 'OpenCV', 'PostgreSQL'],
    features: ['Real-time face recognition pipeline', '15-min stateful presence tracker', 'Privacy-by-design (embeddings only)'],
    node_frontend: 'Next.js Admin',
    node_frontend_details: 'Real-time websocket dashboard showing live attendance status per classroom.',
    node_api: 'FastAPI WebSockets',
    node_api_details: 'High-throughput endpoints receiving embedding vectors from edge cameras.',
    node_backend: 'Matching Engine',
    node_backend_details: 'Performs cosine similarity searches across student embedding databases.',
    node_db: 'PostgreSQL (pgvector)',
    node_db_details: 'Utilizes vector extensions for rapid nearest-neighbor face matching.',
    engineering_decisions: ['Edge computing for raw video processing', 'Vector database for instant matching', 'Websockets for live UI updates'],
    request_flow: ['Edge Camera', 'Embedding Extractor', 'FastAPI Vector Search', 'Next.js UI'],
    capabilities: ['Facial Recognition', 'Vector Search', 'Live Websockets'],
    scale: 'High-Throughput Streams',
    image: '/images/trackademic_card_img.png',
    links: { github: 'https://github.com/dhyey2402/Trackademic-AI', live: '#', video: '#' },
  },
];

export const CONTACT = {
  email: 'dhyeyp060@gmail.com',
  location: 'Ahmedabad, India',
  github: 'https://github.com/dhyey2402',
  linkedin: 'https://www.linkedin.com/in/dhyey-patel-1b304b306/',
};
